# -*- coding: utf-8 -*-
"""Write docs/LEVELS.md, the 100-level table, from the baked src/levels.js."""
import io, os, json, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = io.open(os.path.join(ROOT, 'src', 'levels.js'), encoding='utf-8').read()
levels = json.loads(re.search(r'const LEVELS = (\[.*\]);', src, re.S).group(1))
scenes = {'meadow': "Fool's Meadow", 'pond': 'Moon Pond', 'attic': 'Star Attic', 'tearoom': 'Tea Room', 'cave': 'Crystal Cave',
          'garden': 'Zodiac Garden', 'space': 'Planet Walk', 'temple': 'Temple of Cups', 'clouds': 'Cloud Kingdom', 'tower': "Nabu's Observatory"}
kinds = {'color': 'colour', 'variant': 'detail', 'remove': 'missing', 'flip': 'flipped', 'rotate': 'turned', 'scale': 'size', 'move': 'moved', 'swap': 'swapped'}
out = ['# The 100 levels', '',
       'Generated by `python tools/level_table.py` from the baked `src/levels.js`. Par is the time for 3 stars; '
       'the last column lists every change in picture B (object names are motif ids).']
for ch in range(1, 11):
    ls = [l for l in levels if l['ch'] == ch]
    out.append('\n### Chapter %d · %s\n' % (ch, scenes[ls[0]['bg']]))
    out.append('| # | Level | Rule | Find | Objects | Timer | Max misses | Par | What changes |')
    out.append('|---|---|---|---|---|---|---|---|---|')
    for l in ls:
        rule = 'Similarities (bonus)' if l['type'] == 'same' else 'Mirror' if l.get('mirror') else 'Differences'
        if l['type'] == 'same':
            what = 'find the %d unchanged objects among %d' % (len(l['keep']), len(l['objs']))
        else:
            what = ', '.join(kinds[m['k']] + ' ' + l['objs'][m['i']]['m'] for m in l['muts'])
        out.append('| %d | %d-%d | %s | %d | %d | %s | %d | %ds | %s |' % (
            l['id'], l['ch'], l['n'], rule, l['find'], len(l['objs']), ('%ds' % l['time']) if l['time'] else 'none', l['miss'], l['par'], what))
io.open(os.path.join(ROOT, 'docs', 'LEVELS.md'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('docs/LEVELS.md written (%d levels)' % len(levels))
