# -*- coding: utf-8 -*-
"""Write docs/LEVELS.md, the level table, from the baked src/levels.js."""
import io, os, json, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = io.open(os.path.join(ROOT, 'src', 'levels.js'), encoding='utf-8').read()
levels = json.loads(re.search(r'const LEVELS = (\[.*?\]);\s*\n', src, re.S).group(1))
import sys as _s; _s.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from scenes_ai import SURFACES as _SF
BG = [x[0] for x in _SF]
scenes = {x[0]: x[1]['en'] for x in _SF}
pk = {'hue': 'colour shift', 'flip': 'mirrored patch', 'rotate': 'turned patch', 'scale': 'enlarged patch', 'clone': 'cloned detail',
      'erase': 'erased detail', 'light': 'added glow', 'bright': 'brightness', 'same': 'unchanged light'}
out = ['# The 200 levels', '',
       'Generated by `python tools/level_table.py` from the baked `src/levels.js`. Each picture is composed from '
       'painted objects placed on a painted surface, so every difference is a whole object. Par is the time for 3 stars.']
for ch in range(1, 21):
    ls = [l for l in levels if l['ch'] == ch]
    out.append('\n### Chapter %d · %s\n' % (ch, scenes[ls[0].get('bg') or BG[ch - 1]]))
    out.append('| # | Level | Rule | Find | Surface | Timer | Max misses | Par | What changes |')
    out.append('|---|---|---|---|---|---|---|---|---|')
    for l in ls:
        rule = 'Similarities (bonus)' if l['type'] == 'same' else 'Mirror' if l.get('mirror') else 'Differences'
        what = ('find the %d objects that stayed the same' % l['find']) if l['type'] == 'same' else ', '.join(l.get('kinds', []))
        out.append('| %s | %d-%d | %s | %d | %s | %s | %d | %ds | %s |' % (
            l['id'], l['ch'], l['n'], rule, l['find'], l.get('bg', ''), ('%ds' % l['time']) if l['time'] else 'none', l['miss'], l['par'], what))
io.open(os.path.join(ROOT, 'docs', 'LEVELS.md'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('docs/LEVELS.md written (%d levels)' % len(levels))
